"""Initial migration

Revision ID: 4d17cf77ec5f
Revises: c45421739d96
Create Date: 2025-06-25 13:44:16.314902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d17cf77ec5f'
down_revision: Union[str, Sequence[str], None] = 'c45421739d96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employe', sa.Column('address', sa.String(), nullable=True))
    op.add_column('employe', sa.Column('postal_code', sa.String(length=10), nullable=True))
    op.add_column('employe', sa.Column('mobile_num', sa.String(length=15), nullable=True))
    op.add_column('employe', sa.Column('country', sa.String(length=60), nullable=True))
    op.create_index(op.f('ix_employe_address'), 'employe', ['address'], unique=False)
    op.create_index(op.f('ix_employe_country'), 'employe', ['country'], unique=False)
    op.create_index(op.f('ix_employe_mobile_num'), 'employe', ['mobile_num'], unique=False)
    op.create_index(op.f('ix_employe_postal_code'), 'employe', ['postal_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_employe_postal_code'), table_name='employe')
    op.drop_index(op.f('ix_employe_mobile_num'), table_name='employe')
    op.drop_index(op.f('ix_employe_country'), table_name='employe')
    op.drop_index(op.f('ix_employe_address'), table_name='employe')
    op.drop_column('employe', 'country')
    op.drop_column('employe', 'mobile_num')
    op.drop_column('employe', 'postal_code')
    op.drop_column('employe', 'address')
    # ### end Alembic commands ###
