"""Initial migration

Revision ID: ed06cfbca0ad
Revises: 4d17cf77ec5f
Create Date: 2025-06-26 01:06:27.717702

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed06cfbca0ad'
down_revision: Union[str, Sequence[str], None] = '4d17cf77ec5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employe', sa.Column('otp', sa.String(length=4), nullable=True))
    op.drop_index(op.f('ix_employe_email'), table_name='employe')
    op.create_index(op.f('ix_employe_email'), 'employe', ['email'], unique=True)
    op.create_index(op.f('ix_employe_otp'), 'employe', ['otp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_employe_otp'), table_name='employe')
    op.drop_index(op.f('ix_employe_email'), table_name='employe')
    op.create_index(op.f('ix_employe_email'), 'employe', ['email'], unique=False)
    op.drop_column('employe', 'otp')
    # ### end Alembic commands ###
